/**
 * Catálogo centralizado de códigos de error del dominio.
 * Se usa en Problem Details RFC 9457 y en el cliente REST.
 */
export const ErrorCodes = {
  // Auth
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_JWT: 'INVALID_JWT',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Orders
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_ACCEPTED: 'ORDER_ALREADY_ACCEPTED',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  OUTSIDE_OPERATING_HOURS: 'OUTSIDE_OPERATING_HOURS',
  DRIVER_CAPACITY_EXCEEDED: 'DRIVER_CAPACITY_EXCEEDED',
  RACE_CONDITION: 'RACE_CONDITION',
  PREP_TIME_EXTENSION_LIMIT: 'PREP_TIME_EXTENSION_LIMIT',

  // Restaurants
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  RESTAURANT_BLOCKED: 'RESTAURANT_BLOCKED',
  ACCENT_COLOR_TAKEN: 'ACCENT_COLOR_TAKEN',

  // Drivers
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  DRIVER_NOT_AVAILABLE: 'DRIVER_NOT_AVAILABLE',
  DRIVER_OUT_OF_SHIFT: 'DRIVER_OUT_OF_SHIFT',

  // Cash
  CASH_NOT_PENDING: 'CASH_NOT_PENDING',
  CASH_AMOUNT_MISMATCH: 'CASH_AMOUNT_MISMATCH',

  // Settlements
  SETTLEMENT_ALREADY_PAID: 'SETTLEMENT_ALREADY_PAID',
  SETTLEMENT_PERIOD_OVERLAP: 'SETTLEMENT_PERIOD_OVERLAP',

  // Push
  INVALID_PUSH_SUBSCRIPTION: 'INVALID_PUSH_SUBSCRIPTION',

  // Tracking
  TRACKING_NOT_AVAILABLE: 'TRACKING_NOT_AVAILABLE',

  // Infra
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

export type ProblemDetails = {
  type: string
  title: string
  status: number
  code: ErrorCode
  detail?: string
  instance?: string
  requestId?: string
  errors?: Record<string, string[]>
}
